language: c

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - clang
      - valgrind

script: make test

compiler:
  - clang
  - gcc

env:
  - AMALGAMATED=1
  - STANDARD=1

matrix:
  include:
    # osx build
    - os: osx
      compiler: clang
      env: "OSX=1"
    - os: linux
      compiler: gcov
      env: "STANDARD=1"
      addons:
        - apt:
            packages:
              - valgriand


